---

language: python
python: "2.7"

env:
  global:
    - ROLE_NAME: docker-kibana
  matrix:
    - MOLECULE_DISTRO=ubuntu1604
    - MOLECULE_DISTRO=ubuntu1804
    # - MOLECULE_DISTRO=debian8 MOLECULE_INIT_CMD=/lib/systemd/systemd
    # - MOLECULE_DISTRO=debian9 MOLECULE_INIT_CMD=/lib/systemd/systemd
    # - MOLECULE_DISTRO=centos6 MOLECULE_INIT_CMD=/lib/systemd/systemd
    # - MOLECULE_DISTRO=centos7 MOLECULE_INIT_CMD=/lib/systemd/systemd

before_install:
  - cd ../
  - mv ansible-role-$ROLE_NAME abhi8080.$ROLE_NAME
  - cd abhi8080.$ROLE_NAME

install:
  - pip install docker molecule

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/