---

- name: create kibana dirs
  file:
    path: "{{ item|safe|trim }}"
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: 0777
    recurse: true
  changed_when: false
  with_items:
    - "{{ kibana_config_dir }}"

- name: create kibana configuration file
  template:
    dest: "{{ kibana_config_dir }}/{{ item | basename }}"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: 0644
    force: true
    src: "{{ item }}"
  with_items:
    - kibana.yml

#-------- Unsure if this is needed ---------#

#- name: set vm.max_map_count to 262144 in sysctl
 # sysctl:
  #  name: "{{ item.key }}"
   # value: "{{ item.value }}"
  #with_items:
   # - {key: "vm.max_map_count", value: "262144"}
