---


- name: Ensure Kibana configuration directory exists
  file:
    path: "{{ kibana_config_dir }}"
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: '0777'
    recurse: true
  changed_when: false

- name: Create Kibana configuration file
  template:
    dest: "{{ kibana_config_dir }}/kibana.yml"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: '0644'
    src: "kibana.yml"
  changed_when: false


#-------- Unsure if this is needed ---------#

#- name: set vm.max_map_count to 262144 in sysctl
 # sysctl:
  #  name: "{{ item.key }}"
   # value: "{{ item.value }}"
  #with_items:
   # - {key: "vm.max_map_count", value: "262144"}
