---

- name: Deploy Kibana script
  copy:
    src: "kibana"
    dest: /usr/local/bin/kibana
    mode: '0755'
    owner: root
    group: root

- name: Deploy Kibana systemd service file
  copy:
    src: "kibana.service"
    dest: /etc/systemd/system/kibana.service
    mode: '0644'
    owner: root
    group: root
  notify: kibana restart service