---

- name: Restart the kibana service
  systemd:
    name: kibana
    state: restarted
    enabled: true
    daemon_reload: true
  listen: kibana restart service

- name: Check kibana was started succesfully
  uri:
    url: "http://{{ kibana_config.server.host }}:{{ kibana_config.server.port }}"
    return_content: true
    validate_certs: true
  register: result
  until: result is success
  retries: 60
  delay: 10
  failed_when:
    - result is failed
    - result.status != 200
  listen: kibana restart service

